# Generated by Django 3.1.7 on 2021-03-16 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=100)),
                ('law_school_name', models.CharField(max_length=100)),
                ('law_school_degree', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('non law', 'Non law'), ('paralegal', 'Paralegal'), ('associate', 'Associate'), ('partner', 'Partner'), ('Named', 'Named')], max_length=45)),
                ('joning_date', models.DateField()),
                ('scale', models.IntegerField()),
                ('grade_of_post', models.CharField(max_length=45)),
                ('first_time_scale_due_year', models.IntegerField(blank=True, null=True)),
                ('second_time_scale_due_year', models.IntegerField(blank=True, null=True)),
                ('promotion_due_year', models.IntegerField(blank=True, null=True)),
                ('recreation_leave_due_year', models.IntegerField(blank=True, null=True)),
                ('expected_retirement_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('photo', models.ImageField(upload_to='')),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=45)),
                ('nationality', models.CharField(choices=[('Nigerian', 'Nigerian'), ('Others', 'Others')], max_length=45)),
                ('religion', models.CharField(choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Others', 'Others')], max_length=45)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(choices=[('a+', 'A+'), ('o+', 'O+'), ('b+', 'B+'), ('ab+', 'AB+'), ('a-', 'A-'), ('o-', 'O-'), ('b-', 'B-'), ('ab-', 'AB-')], max_length=5)),
                ('driving_license_passport', models.IntegerField(unique=True)),
                ('phone_no', models.CharField(max_length=11, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('father_name', models.CharField(max_length=45)),
                ('mother_name', models.CharField(max_length=45)),
                ('marital_status', models.CharField(choices=[('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('divorced', 'Divorced'), ('single', 'Single')], max_length=10)),
                ('is_delete', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyers.backgroundinfo')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyers.jobinfo')),
                ('login_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
