# Generated by Django 3.1.7 on 2021-03-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('non law', 'Non law'), ('paralegal', 'Paralegal'), ('associate', 'Associate'), ('partner', 'Partner'), ('Named', 'Named')], max_length=45)),
                ('joning_date', models.DateField()),
                ('university_name', models.CharField(max_length=100)),
                ('law_school_name', models.CharField(max_length=100)),
                ('scale', models.IntegerField()),
                ('grade_of_post', models.CharField(max_length=45)),
                ('first_time_scale_due_year', models.IntegerField()),
                ('second_time_scale_due_year', models.IntegerField()),
                ('promotion_due_year', models.IntegerField()),
                ('recreation_leave_due_year', models.IntegerField()),
                ('expected_retirement_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=54)),
                ('photo', models.ImageField(upload_to='')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female')], max_length=7)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('father_name', models.CharField(max_length=45)),
                ('mother_name', models.CharField(max_length=45)),
                ('marital_status', models.CharField(choices=[('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('divorced', 'Divorced'), ('single', 'Single')], max_length=10)),
            ],
        ),
    ]
