# Generated by Django 3.1.7 on 2021-03-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobinfo',
            name='recreation_leave_due_year',
        ),
        migrations.RemoveField(
            model_name='jobinfo',
            name='scale',
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='promotion_due_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
